version: "2"
services:
  web:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/app
    ports:
      - "3000:3000"
    depends_on:
      - database
      
  database:
    image: postgres:9.5
    ports:
      - "3001:5432"
    environment:
      POSTGRES_DB: jaya
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin