version: "2"
services:
  web:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/app
    ports:
      - "3000:3000"
    links:
      - database:db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: jaya
      DB_USER: admin
      DB_PASSWORD: admin
      DATABASE_URI: postgres://admin:admin@db:5432/jaya
      
  database:
    image: postgres:9.5
    ports:
      - "3001:5432"
    environment:
      POSTGRES_DB: jaya
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin